### ISSUE TITLE
Currently hosted conda packages are behind commited versions

### ISSUE THREAD

**Issue by nlysne** [m-labs/lda#2]
# Bug Report
## One Line Summary
Current stable version packages hosted on conda for `lda` with `ARTIQ v7.8116` do not have critical fixes pushed in commit `2d8af1e`.  @sbourdeauducq 

### Steps to Reproduce
1. Follow instructions for setting up a new conda environment with `ARTIQ v7.8116`.
2. Attempt to use `lda` firmware, or inspect `lda\hidapi.py` file in site package.

### Expected Behavior
Fix to `path` variable should be present.

### Actual (undesired) Behavior
`path` is not `hidapi_lib_path` and cannot find necessary modules to run.

### Your System
- Operating System: Windows 11
- ARTIQ Version: `ARTIQ v7.8116.eba143a`
- Gateware etc: n/a
- Conda Environment: [conda_list.txt](https://github.com/m-labs/lda/files/9499568/conda_list.txt)
- Hardware Involved: LabBrick Digital Attenuator `LDA-102`

**Comment by sbourdeauducq** [comment]
https://git.m-labs.hk/M-Labs/artiq-extrapkg/commit/5c519374505e75cd088f846a7836c8abda4a3458
